spring:
  application:
    name: ms-property-access-service
  config:
    import: optional:configserver:http://localhost:8889
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS

server:
  port: ${port:8100}


management:
  endpoints:
    web:
      exposure:
        include: refresh